databases:
  - name: leavemanager-db
    databaseName: leavemanager
    user: leavemanager
    plan: free

services:
  - type: web
    name: leave-manager
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: leavemanager-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: leavemanager-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: leavemanager-db
          property: password
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
